export const CHANGE_GENDER = "CHANGE_GENDER";
export const GET_USER_INFO = "GET_USER_INFO";
export const CHOOSE_SIZE = "CHOOSE_SIZE";
export const CHOOSE_SIZE_BY_SIZE = "CHOOSE_SIZE_BY_SIZE";
export const IS_CHANGE_BOOLEAN = "IS_CHANGE_BOOLEAN";
export const FETCH_LOAD_SETTING = "FETCH_LOAD_SETTING";
export const CONNECT_LOAD_USER_INFO = "CONNECT_LOAD_USER_INFO";
export const GET_DATA = "GET_DATA";
export const SET_NEW_INIT_DATA = 'SET_NEW_INIT_DATA';
export const SET_CURRENT_ID = 'SET_CURRENT_ID';
export const SET_DATA_ON_CHANGE_COLOR = 'SET_DATA_ON_CHANGE_COLOR';
export const SET_DATA_ON_CHANGE_SIZE = 'SET_DATA_ON_CHANGE_SIZE';
export const SET_SIZE_CHART = 'SET_SIZE_CHART';
export const SET_LIKE = 'SET_LIKE';




